-- Supabase Database Schema for WattWave

-- 1. Create DEVICES table (for state persistence)
CREATE TABLE IF NOT EXISTS public.devices (
    id TEXT PRIMARY KEY,
    relay_state BOOLEAN DEFAULT false,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create READINGS table (for telemetry history)
CREATE TABLE IF NOT EXISTS public.readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT REFERENCES public.devices(id) ON DELETE CASCADE,
    voltage REAL NOT NULL,
    current REAL NOT NULL,
    power REAL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Initial Data (Plug 1, 2, 3)
INSERT INTO public.devices (id, relay_state)
VALUES 
    ('plug_1', false),
    ('plug_2', false),
    ('plug_3', false)
ON CONFLICT (id) DO NOTHING;

-- 4. RLS (Row Level Security) - Simplified for Public Access
-- Enable RLS on both tables
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.readings ENABLE ROW LEVEL SECURITY;

-- 5. Policies
CREATE POLICY "Public Read Access" ON public.devices FOR SELECT USING (true);
CREATE POLICY "Public Update Access" ON public.devices FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Public Read Access" ON public.readings FOR SELECT USING (true);
CREATE POLICY "Public Insert Access" ON public.readings FOR INSERT WITH CHECK (true);

-- 6. Auth Attempts (Brute-force protection)
CREATE TABLE IF NOT EXISTS public.auth_attempts (
    ip TEXT PRIMARY KEY,
    attempts INTEGER DEFAULT 0,
    lockout_until TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.auth_attempts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Auth Access" ON public.auth_attempts FOR ALL USING (true) WITH CHECK (true);
